version: '3.8'

services:
  leakcheck-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - LEAKCHECK_API_KEY=${LEAKCHECK_API_KEY}
    volumes:
      - .:/app
    restart: unless-stopped